apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payrollapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payrollapp
    spec:
      containers:
        - image: "my-registry:5000/accountownerapp:B1"
          imagePullPolicy: Always
          name: payrollapp
          ports:
            - containerPort: 80
